name: simple_gravatar
version: 1.1.0
author: Alif Rachmawadi <arch@subosito.com>
description: A library to generate Gravatar URL in Dart 2 based on gravatar specs.
homepage: https://github.com/subosito/simple_gravatar
dependencies:
  crypto: ^3.0.0
dev_dependencies:
  test: ^1.16.8
environment:
  sdk: '>=2.12.0 <3.0.0'
